# Basic Information 
title: Samee Arif
position: Research Associate
affiliation: Lahore University of Management Sciences (LUMS)
email: samee.arif (at) lums.edu.pk

# Search Engine Optimization (SEO)
keywords: Samee Arif, LUMS, Computer Science
description: Samee Arif is a Research Associate at Lahore University of Management Sciences (LUMS). His research interests lie in applied machine learning, multilingual and multimodal natural language processing and human-centric technologies.

# Links 
# cv_link: assets/files/cv.pdf
github_link: https://github.com/sameearif
linkedin: https://www.linkedin.com/sameearif
# medium: https://medium.com/@mutahar789

# Images
avatar: ./assets/img/me.jpeg
favicon: ./assets/img/favicon.webp
favicon_dark: ./assets/img/favicon-dark.webp

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
